openapi: 3.0.0

# Server specificatie
servers:
  - description: LVBAG - TEST
    url: https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1
  - description: LVBAG - ACCEPTATIE
    url: https://api.acceptatie.kadaster.nl/lvbag/api/individuelebevragingen/v1
  - description: LVBAG - PRODUCTIE
    url: https://api.kadaster.nl/lvbag/api/individuelebevragingen/v1

# API specificatie - algemeen
info:
  title: IMBAG API - van de LVBAG
  description: "Dit is de BAG API van de landelijke voorziening BAG (LVBAG) voor het informatiemodel IMBAG 2.0 en conform de API strategie 1.1 specificatie in OAS3. Deze is vooral gericht op individuele bevragingen (op basis van de identificerende gegevens van een object).
    <br/><br/>
    <font color='red'>**LET OP: Deze specificatie is een \"work in progress\"**, oftewel niet definitief.</font><br/><br/>
    Meer informatie over BAG 2.0 is te vinden op: [Catalogus BAG 2.0](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen)
    <br/>
    Meer informatie over Nederlandse API strategie is te vinden op: [API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie) - deze API volgt versie 1.1 van 20190213.
    <br/>
    Meer informatie over OAS3 specificatie is te vinden op: [OAS](https://www.forumstandaardisatie.nl/standaard/openapi-specification)
    <br/>
    Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
    <br/>
    <br/>
    Voor vragen, neem contact op met de BAG beheerder o.v.v. BAG API 2.0. We zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets (nog) niet kan, wat u wel graag wilt, neem dan contact op.
    <br/>
    <br/>
    Een API-key kan  verkregen worden door een e-mail te sturen naar: zie onderstaande contactgegevens <font color='blue'>send e-mail</font>."

  version: '0.1'
  # De versie wordt 1.0 als de API naar productie gaat.
  termsOfService: https://zakelijk.kadaster.nl/algemene-voorwaarden
  contact:
    name: Kadaster - Beheerder Landelijke Voorziening BAG
    email: bag@kadaster.nl
    url: https://zakelijk.kadaster.nl/bag
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/

security:
  - apiKeyBAG: []
  # Alle requests verwachten een (BAG) API key (niet per operation of end-point veschillend)
  # Voor defintie van benoemde 'apiKeyBAG', zie security-schemes onderin.

#+Functionele toelichting bij de operations/end-points als documentatie indeling.
tags:
  -
    name: Bronhouder
    description: 'Dit endpoint levert één of meer bronhouder(s).'

paths:

  # Vraag bronhouder
  /bronhouders/{identificatie}:
    get:
      security:
        - apiKeyBAG: []
      tags:
        - Bronhouder
      summary: 'Bevragen bronhouder, op basis van de bronhouder identificatie (gemeentecode).'
      operationId: bevragenBronhouder
      description: >-
        "Bevragen/raadplegen van een bronhouder, via de identificatie van een bronhouder (gemeentecode).
         Geleverd wordt een bronhouder.
         Parameter identificatie bevat de 4 cijferige identificatie van een bronhouder (gemeentecode).
         Als geldigOp en/of beschikbaarOp niet wordt opgegeven, worden de actuele gegevens geleverd."
      parameters:
        - $ref: '#/components/parameters/identificatie'
        - $ref: '#/components/parameters/geldigOp'
        - $ref: '#/components/parameters/beschikbaarOp'

      # Antwoord bevragenBronhouder
      responses:
        '200':
          description: Bevraging bronhouder geslaagd
          headers:
            api-version: #Is dit wel API strategie?
              $ref: '../../../../generiek/headers.yaml#/api_version'
            warning:
              $ref: '../../../../generiek/headers.yaml#/warning'
            X-Rate-Limit-Limit:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Reset'
          content:
            application/hal+json:
              schema:
                $ref: './resources.yaml#/Bronhouder'
        '204':
          $ref: '../../../../generiek/responses.yaml#/204'
        '400':
          $ref: '../../../../generiek/responses.yaml#/400'
        '401':
          $ref: '../../../../generiek/responses.yaml#/401'
        '403':
          $ref: '../../../../generiek/responses.yaml#/403'
        '404':
          $ref: '../../../../generiek/responses.yaml#/404'
        '410':
          $ref: '../../../../generiek/responses.yaml#/410'
        '415':
          $ref: '../../../../generiek/responses.yaml#/415'
        '422':
          $ref: '../../../../generiek/responses.yaml#/422'
        '429':
          $ref: '../../../../generiek/responses.yaml#/429'
        '500':
          $ref: '../../../../generiek/responses.yaml#/500'
        default:
          $ref: '../../../../generiek/responses.yaml#/default'

  # Vraag bronhouderGeometrie
  /bronhouders:
    post:
      requestBody:
        description: Geometrisch punt waarvoor de bronhouder(s) bepaald moeten worden.
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../../geometrie/geometrie.yaml#/components/schemas/Point'
      security:
        - apiKeyBAG: []
      tags:
        - Bronhouder
      summary: 'bevragen 1 bronhouder, op basis van de geometrische locatie.'
      operationId: bronhouderGeometrie
      description: >-
        Bevragen/raadplegen van eenn bronhouder, via een geometrische lcoatie.
        Geleverd wordt een bronhouder.
        Als geldigOp en/of beschikbaarOp niet wordt opgegeven, worden de actuele gegevens geleverd.
        De contentCrs in de header moet zijn epsg:28992
      parameters:
        - $ref: '#/components/parameters/geldigOp'
        - $ref: '#/components/parameters/beschikbaarOp'
        - $ref: '../../../../generiek/headers.yaml#/contentCrs'

      # Antwoord bronhouderGeometrie
      responses:
        '200':
          description: Bevraging bronhouderGeometrie geslaagd
          headers:
            api-version: #Is dit wel API strategie?
              $ref: '../../../../generiek/headers.yaml#/api_version'
            warning:
              $ref: '../../../../generiek/headers.yaml#/warning'
            X-Rate-Limit-Limit:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Reset'
            Accept-Crs:
              $ref: '../../../../generiek/headers.yaml#/acceptCrs'
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: './resources.yaml#/Bronhouder'
                minItems: 1
        '204':
          $ref: '../../../../generiek/responses.yaml#/204'
        '400':
          $ref: '../../../../generiek/responses.yaml#/400'
        '401':
          $ref: '../../../../generiek/responses.yaml#/401'
        '403':
          $ref: '../../../../generiek/responses.yaml#/403'
        '404':
          $ref: '../../../../generiek/responses.yaml#/404'
        '405':
          $ref: '../../../../generiek/responses.yaml#/405'
        '406':
          $ref: '../../../../generiek/responses.yaml#/406'
        '410':
          $ref: '../../../../generiek/responses.yaml#/410'
        '412':
          $ref: '../../../../generiek/responses.yaml#/412'
        '415':
          $ref: '../../../../generiek/responses.yaml#/415'
        '422':
          $ref: '../../../../generiek/responses.yaml#/422'
        '429':
          $ref: '../../../../generiek/responses.yaml#/429'
        '500':
          $ref: '../../../../generiek/responses.yaml#/500'
        '503':
          $ref: '../../../../generiek/responses.yaml#/503'
        default:
          $ref: '../../../../generiek/responses.yaml#/default'

    # Zoek bronhouder
    get:
      security:
        - apiKeyBAG: []
      tags:
        - Bronhouder
      summary: 'Bevragen bronhouder, op basis van de object identificatie.'
      operationId: zoekBronhouder
      description: >-
        "Bevragen/raadplegen van een bronhouder, via de identificatie van een object.
         Geleverd wordt een bronhouder.
         Één van de onderstaande parameters dient gespecificeerd te worden:<br/>
         Parameter woonplaatsIdentificatie bevat de 4 cijferige identificatie van een woonplaats object.<br/>
         Parameter openbareRuimteIdentificatie bevat de 16 cijferige identificatie van een openbare ruimte object.<br/>
         Parameter nummeraanduidingIdentificatie bevat de 16 cijferige identificatie van een nummeraanduiding object.<br/>
         Parameter ligplaatsIdentificatie bevat de 16 cijferige identificatie van een ligplaats.<br/>
         Parameter standplaatsIdentificatie bevat de 16 cijferige identificatie van een standplaats.<br/>
         Parameter verblijfsobjectIdentificatie bevat de 16 cijferige identificatie van een verblijfsobject.<br/>
         Parameter pandIdentificatie bevat de 16 cijferige identificatie van een pand.<br/>
         Als geldigOp en/of beschikbaarOp niet wordt opgegeven, worden de actuele gegevens geleverd.<br/>
         De contentCrs in de header moet zijn epsg:28992"
      parameters:
        - $ref: '#/components/parameters/woonplaatsIdentificatie'
        - $ref: '#/components/parameters/openbareRuimteIdentificatie'
        - $ref: '#/components/parameters/nummeraanduidingIdentificatie'
        - $ref: '#/components/parameters/ligplaatsIdentificatie'
        - $ref: '#/components/parameters/standplaatsIdentificatie'
        - $ref: '#/components/parameters/verblijfsobjectIdentificatie'
        - $ref: '#/components/parameters/pandIdentificatie'
        - $ref: '#/components/parameters/geldigOp'
        - $ref: '#/components/parameters/beschikbaarOp'
        - $ref: '../../../../generiek/headers.yaml#/contentCrs'

      # Antwoord zoekBronhouder
      responses:
        '200':
          description: Bevraging zoekBronhouder geslaagd
          headers:
            api-version:
              $ref: '../../../../generiek/headers.yaml#/api_version'
            warning:
              $ref: '../../../../generiek/headers.yaml#/warning'
            X-Rate-Limit-Limit:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Reset'
            Accept-Crs:
              $ref: '../../../../generiek/headers.yaml#/acceptCrs'
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: './resources.yaml#/Bronhouder'
                minItems: 1
        '204':
          $ref: '../../../../generiek/responses.yaml#/204'
        '400':
          $ref: '../../../../generiek/responses.yaml#/400'
        '401':
          $ref: '../../../../generiek/responses.yaml#/401'
        '403':
          $ref: '../../../../generiek/responses.yaml#/403'
        '404':
          $ref: '../../../../generiek/responses.yaml#/404'
        '405':
          $ref: '../../../../generiek/responses.yaml#/405'
        '406':
          $ref: '../../../../generiek/responses.yaml#/406'
        '410':
          $ref: '../../../../generiek/responses.yaml#/410'
        '412':
          $ref: '../../../../generiek/responses.yaml#/412'
        '415':
          $ref: '../../../../generiek/responses.yaml#/415'
        '422':
          $ref: '../../../../generiek/responses.yaml#/422'
        '429':
          $ref: '../../../../generiek/responses.yaml#/429'
        '500':
          $ref: '../../../../generiek/responses.yaml#/500'
        '503':
          $ref: '../../../../generiek/responses.yaml#/503'
        default:
          $ref: '../../../../generiek/responses.yaml#/default'

components:

  securitySchemes:
    apiKeyBAG:
      type: apiKey
      name: X-Api-Key
      in: header
      description: >
        De API-key die je hebt gekregen dient bij elke request via de 
        `X-Api-Key` request header meegestuurd te worden. Indien deze 
        niet juist wordt meegestuurd, of het een ongeldige key betreft, 
        zul je de foutmelding `403 Forbidden` terugkrijgen.

  parameters:
    # Opsomming van path parameters - /{...} - specificatie bij operation zelf.
    identificatie:
      description: 'Een officiële code die aan een gemeente is toegekend, ontleend is aan tabel 33.'
      name: identificatie
      in: path
      required: true
      schema:
        type: string
        pattern: '^[0-9]{4}$'
        example: '0518'

    # Opsomming van request parameters - ?='...' parameters (by name) - specificatie bij operation zelf.
    woonplaatsIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: woonplaatsIdentificatie
      in: query
      required: false
      schema:
        description: 'Deze wordt gebruikt in de operation, bv. /woonplaatsen/0123. Waarde: 0001-9999, formaat: ^[0-9]{3}[1-9]\|[0-9]{2}[1-9][0-9]\|[0-9][1-9][0-9]{2}\|[1-9][0-9]{3}$.'
        type: string
        pattern: '[0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]|[0-9][1-9][0-9]{2}|[1-9][0-9]{3}'
        example: '0150'

    openbareRuimteIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: openbareRuimteIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}30[0-9]{10}$'
        example: '0518300000000001'

    nummeraanduidingIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: nummeraanduidingIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}20[0-9]{10}$'
        example: '1234200000000001'

    verblijfsobjectIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: verblijfsobjectIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}01[0-9]{10}$'
        example: '1234010000000001'

    ligplaatsIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: ligplaatsIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}02[0-9]{10}$'
        example: '1234020000000001'

    standplaatsIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: standplaatsIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}03[0-9]{10}$'
        example: '1234030000000001' 

    pandIdentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: pandIdentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}10[0-9]{10}$'
        example: '1234100000000001'

    geldigOp:
      description: >
        Filtert op objecten die geldig zijn op de opgegeven datum 'YYYY-MM-DD'
        Deze parameters komen uit de API strategie, het hoofdstuk [tijdreizen](https://docs.geostandaarden.nl/api/API-Strategie/#tijdreizen)
      name: geldigOp
      in: query
      required: false
      schema:
        type: string
        format: date
        example: '2019-06-01'

    beschikbaarOp:
      description: >
        Filtert op objecten die beschikbaar zijn gekomen op de opgegeven datum en tijd `YYYY-MM-DDThh:mm:ss.sss'
        Hierin kunnen de seconden ':ss' en milliseconden '.sss' of alleen de milliseconden confrom ISO 8601 specificatie worden weggelaten, in dat geval krijgen deze automatisch de waarde ':00' respectievelijk '.000'.
        Indien er voor de milliseconden '.sss' meer dan 3 cijfers worden opgegeven, bv. '.12345', dan wordt dit afgekapt tot '.123'.
        Deze parameters komen uit de API strategie, het hoofdstuk [tijdreizen](https://docs.geostandaarden.nl/api/API-Strategie/#tijdreizen)
      name: beschikbaarOp
      in: query
      required: false
      schema:
        type: string
        format: date-time
        example: '2019-06-01T12:00:00.000'
