openapi: 3.0.0

#Server specificatie
servers:
  - description: LVBAG - TEST
    url: https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1
  - description: LVBAG - PRODUCTIE
    url: https://api.kadaster.nl/lvbag/api/individuelebevragingen/v1

#API specificatie - algemeen
info:
  title: BAG Adressen API
  description: >-
    "Dit is de BAG Adres API van de landelijke voorziening BAG (LVBAG) voor het informatiemodel IMBAG 2.0 en conform de API strategie 1.1 specificatie in OAS3. Deze is vooral gericht op individuele bevragingen (op basis van de identificerende gegevens van een object).
    <br/><br/>
    <font color='red'>**LET OP: Deze specificatie is een \"work in progress\"**, oftewel niet definitief.</font><br/><br/>
    Meer informatie over BAG 2.0 is te vinden op: [Catalogus BAG 2.0](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen)
    <br/>
    Meer informatie over Nederlandse API strategie is te vinden op: [API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie) - deze API volgt versie 1.1 van 20190213.
    <br/>
    Meer informatie over OAS3 specificatie is te vinden op: [OAS](https://www.forumstandaardisatie.nl/standaard/openapi-specification)
    <br/>
    Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
    <br/>
    <br/>
    Voor vragen, neem contact op met de BAG beheerder o.v.v. BAG API 2.0. We zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets (nog) niet kan, wat u wel graag wilt, neem dan contact op.
    <br/>
    <br/>
    Een API-key kan  verkregen worden door een e-mail te sturen naar: zie onderstaande contactgegevens <font color='blue'>send e-mail</font>."

  version: '0.1'
  # De versie wordt 1.0 als de API naar productie gaat.
  termsOfService: https://zakelijk.kadaster.nl/algemene-voorwaarden
  contact:
    name: Kadaster - Beheerder Landelijke Voorziening BAG
    email: bag@kadaster.nl
    url: https://zakelijk.kadaster.nl/bag
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/

security:
  - apiKeyBAG: []

tags:
  -
    name: Adres
    description: 'Dit endpoint levert één of meer (voorkomens van) adres(sen)'

paths:
  # Zoek adres
  /adressen/zoeken:
    get:
      security:
        - apiKeyBAG: []
      operationId: zoeken
      tags:
        - Adres
      summary: Zoek adressen o.b.v. verschillende parameters.
      description: Zoeken van adressen via free query op postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging
      parameters:
        - $ref: '#/components/parameters/zoekterm'

      responses:
        '200':
          description: Bevraging zoekAdres geslaagd
          headers:
            api-version:
              $ref: '../../../../generiek/headers.yaml#/api_version'
            warning:
              $ref: '../../../../generiek/headers.yaml#/warning'
            X-Rate-Limit-Limit:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Reset'
            Accept-Crs:
              $ref: '../../../../generiek/headers.yaml#/acceptCrs'
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ZoekSuggestieResponse'
        '204':
          $ref: '../../../../generiek/responses.yaml#/204'
        '400':
          $ref: '../../../../generiek/responses.yaml#/400'
        '401':
          $ref: '../../../../generiek/responses.yaml#/401'
        '403':
          $ref: '../../../../generiek/responses.yaml#/403'
        '404':
          $ref: '../../../../generiek/responses.yaml#/404'
        '405':
          $ref: '../../../../generiek/responses.yaml#/405'
        '406':
          $ref: '../../../../generiek/responses.yaml#/406'
        '410':
          $ref: '../../../../generiek/responses.yaml#/410'
        '412':
          $ref: '../../../../generiek/responses.yaml#/412'
        '429':
          $ref: '../../../../generiek/responses.yaml#/429'
        '500':
          $ref: '../../../../generiek/responses.yaml#/500'
        '503':
          $ref: '../../../../generiek/responses.yaml#/503'
        default:
          $ref: '../../../../generiek/responses.yaml#/default'

  /adressen/:
    get:
      security:
        - apiKeyBAG: []
      operationId: zoekAdres
      tags:
        - Adres
      summary: Zoek adres o.b.v. een sleutel
      description: Zoek adres met een sleutel verkregen via de zoeken-operatie
      parameters:
        - $ref: '#/components/parameters/key'

      responses:
        '200':
          description: Bevraging zoekAdres geslaagd
          headers:
            api-version:
              $ref: '../../../../generiek/headers.yaml#/api_version'
            warning:
              $ref: '../../../../generiek/headers.yaml#/warning'
            X-Rate-Limit-Limit:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '../../../../generiek/headers.yaml#/X_Rate_Limit_Reset'
            Accept-Crs:
              $ref: '../../../../generiek/headers.yaml#/acceptCrs'
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ZoekAdresResponse'
        '204':
          $ref: '../../../../generiek/responses.yaml#/204'
        '400':
          $ref: '../../../../generiek/responses.yaml#/400'
        '401':
          $ref: '../../../../generiek/responses.yaml#/401'
        '403':
          $ref: '../../../../generiek/responses.yaml#/403'
        '404':
          $ref: '../../../../generiek/responses.yaml#/404'
        '405':
          $ref: '../../../../generiek/responses.yaml#/405'
        '406':
          $ref: '../../../../generiek/responses.yaml#/406'
        '410':
          $ref: '../../../../generiek/responses.yaml#/410'
        '412':
          $ref: '../../../../generiek/responses.yaml#/412'
        '429':
          $ref: '../../../../generiek/responses.yaml#/429'
        '500':
          $ref: '../../../../generiek/responses.yaml#/500'
        '503':
          $ref: '../../../../generiek/responses.yaml#/503'
        default:
          $ref: '../../../../generiek/responses.yaml#/default'

components:

  securitySchemes:

    apiKeyBAG:
      type: apiKey
      name: X-Api-Key
      in: header
      description: >
        De API-key die je hebt gekregen dient bij elke request naar deze
        via de `X-Api-Key` request header meegestuurd te worden. Indien deze
        niet juist wordt meegestuurd, of het een ongeldige key betreft, zul je
        de foutmelding `403 Forbidden` terugkrijgen.

  parameters:

    # Opsomming van request parameters - ?='...' parameters (by name) - specificatie bij operation zelf.
    zoekterm:
      description: zoekterm op postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging
      name: query
      in: query
      required: true
      schema:
        type: string

    key:
      description: key verkregen uit zoeksuggestie om meer informatie over dat resultaat op te vragen
      name: key
      in: query
      required: true
      schema:
        type: string

  schemas:

    Adres:
      type: object
      properties:
        straatnaam:
          title: openbareruimte naam
          description: De verkorte versie van een naam die aan een openbare ruimte is toegekend in een daartoe strekkend formeel gemeentelijk besluit.
          type: string
          minLength: 1
          maxLength: 80
          example: 'Laan v Westenenk'
        huisnummer:
          description: Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende nummering.
          title: huisnummer
          type: integer
          minLength: 1
          maxLength: 5
          pattern: '^[1-9][0-9]{0,4}$'
          example: 12
        huisletter:
          description: Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken.
          title: huisletter
          type: string
          maxLength: 1
          pattern: '^[a-zA-Z]{1}$'
          example: A
        huisnummerToevoeging:
          description: Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter.
          title: huisnummer toevoeging
          type: string
          minLength: 1
          maxLength: 4
          pattern: '^[0-9a-zA-Z]{1,4}$'
          example: bis
        postcode:
          title: postcode
          description: De door PostNL vastgestelde code behorende bij een bepaalde combinatie van een straatnaam en een huisnummer.
          type: string
          maxLength: 6
          pattern: '^[1-9]{1}[0-9]{3}[A-Z]{2}$'
          example: 7500AA
        woonplaatsnaam:
          description: De benaming van een door het gemeentebestuur aangewezen woonplaats.
          title: woonplaats naam
          type: string
          minLength: 1
          maxLength: 80
          pattern: '^[\u0020-\u007E;\u00A0-\u00FF;\u0100-\u0113;\u0116-\u012B;\u012E-\u014D;\u0150-\u017E;\u02C7;\u02D8-\u02DB;\u02DD;\u2015;\u2018-\u2019;\u201C-\u201D;\u20AC;\u2122;\u2126;\u215B-\u215E;\u2190-\u2193;\u266A;]*'
          example: Apeldoorn

    Adres_links:
      required:
        - self
      type: object
      properties:
        self:
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'
        # De standaard relatie richting is van openbare ruimte naar woonplaats. Voor andersom is een hulp link nodig.
        openbareRuimten:
          description: 'De gerelateerde openbare ruimte op basis waarvan het adres is samengesteld.'
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'
        nummeraanduidingen:
          description: 'De gerelateerde nummeraanduiding op basis waarvan het adres is samengesteld.'
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'
        woonplaatsen:
          description: 'De gerelateerde woonplaats op basis waarvan het adres is samengesteld.'
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'
        verblijfsobjecten:
          description: 'De gerelateerde verblijfsobjecten op basis waarvan het adres is samengesteld.'
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'
        panden:
          description: 'De gerelateerde panden op basis waarvan het adres is samengesteld.'
          $ref: '../../../../generiek/hallinks.yaml#/HalLink'

    ZoekSuggestie:
      type: object
      properties:
        type:
          description: 'Type van gevonden zoeksuggestie'
          title: 'type'
          type: string
        weergavenaam:
          description: 'Weergavenaam van de zoeksuggestie'
          title: 'weergavenaam'
          type: string
        id:
          description: 'Id van de zoeksuggestie'
          title: 'id'
          type: string
        score:
          description: 'Score van de zoeksuggestie. Hoger is dichterbij de zoekterm'
          title: 'score'
          type: number

    ZoekSuggestieResponse:
      description: 'Lijst van suggestie op basis van een zoekstring'
      title: ZoekSuggestieResponse
      type: object
      properties:
        resultCount:
          description: 'aantal gevonden resultaten'
          title: resultCount
          type: integer
        resultStart:
          description: 'nummer van het eerste resultaat in de lijst'
          title: resultStart
          type: integer
        maxScore:
          description: 'hoogste score van de suggesties'
          title: maxScore
          type: number
        idStringPairs:
          description: 'resulaten als lijst'
          title: idStringPairs
          type: array
          items:
            $ref: '#/components/schemas/ZoekSuggestie'

    ZoekAdresResponse:
      description: 'Een combinatie van beperkt adres en Ids van de resources op basis waarvan het beperkte adres is samengesteld'
      title: 'ZoekAdresResponse'
      type: object
      properties:
        adres:
          $ref: '#/components/schemas/Adres'
        _links:
          $ref: '#/components/schemas/Adres_links'
